name: Zip Specific Folders on Changes

on:
  push:
    paths:
      - 'sphax_patch_pack/x32-TCP-Sphax_PatchPack/**'
      - 'sphax_patch_pack/x64-TCP-Sphax_PatchPack/**'
      - 'sphax_patch_pack/x128-TCP-Sphax_PatchPack/**'
  workflow_dispatch:

jobs:
  zip-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        
      - name: Set up Git LFS
        run: |
          git lfs install
          git lfs track "*.zip"  # Track .zip files with Git LFS

      - name: Create zip for x32-TCP-Sphax_PatchPack
        run: |
          cd sphax_patch_pack/x32-TCP-Sphax_PatchPack
          zip -r ../x32-TCP-Sphax_PatchPack.zip ./*

      - name: Create zip for x64-TCP-Sphax_PatchPack
        run: |
          cd sphax_patch_pack/x64-TCP-Sphax_PatchPack
          zip -r ../x64-TCP-Sphax_PatchPack.zip ./*

      - name: Create zip for x128-TCP-Sphax_PatchPack
        run: |
          cd sphax_patch_pack/x128-TCP-Sphax_PatchPack
          zip -r ../x128-TCP-Sphax_PatchPack.zip ./*

      - name: List files in sphax_patch_pack
        run: |
          ls -al sphax_patch_pack/

      - name: Commit and push the .zip files to the repository with Git LFS
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add sphax_patch_pack/*.zip
          git commit -m "Add .zip files for patched folders"
          git push origin master  # Adjust branch if necessary (e.g., main)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
