name: Zip Specific Folders on Changes

on:
  push:
    paths:
      - 'sphax_patch_pack/x32-TCP-Sphax_PatchPack/**'
      - 'sphax_patch_pack/x64-TCP-Sphax_PatchPack/**'
      - 'sphax_patch_pack/x128-TCP-Sphax_PatchPack/**'
  workflow_dispatch:

jobs:
  zip-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Create zip for x32-TCP-Sphax_PatchPack
        run: |
          zip -r sphax_patch_pack/x32-TCP-Sphax_PatchPack.zip sphax_patch_pack/x32-TCP-Sphax_PatchPack/*

      - name: Create zip for x64-TCP-Sphax_PatchPack
        run: |
          zip -r sphax_patch_pack/x64-TCP-Sphax_PatchPack.zip sphax_patch_pack/x64-TCP-Sphax_PatchPack/*

      - name: Create zip for x128-TCP-Sphax_PatchPack
        run: |
          zip -r sphax_patch_pack/x128-TCP-Sphax_PatchPack.zip sphax_patch_pack/x128-TCP-Sphax_PatchPack/*

      - name: List files in sphax_patch_pack
        run: |
          ls -al sphax_patch_pack/

      - name: Commit and push the .zip files to the repository
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add sphax_patch_pack/*.zip
          git commit -m "Add .zip files for patched folders"
          git push origin master  # Make sure this pushes to the correct branch (e.g., `main` or `master`)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}