name: Zip Specific Folders on Changes

on:
  push:
    paths:
      - 'sphax_patch_pack/x32-TCP-Sphax_PatchPack/**'
      - 'sphax_patch_pack/x64-TCP-Sphax_PatchPack/**'
      - 'sphax_patch_pack/x128-TCP-Sphax_PatchPack/**'
  workflow_dispatch:

jobs:
  zip-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Git LFS
        run: |
          git lfs install
          git lfs track "*.zip"  # Track .zip files with Git LFS

      - name: Prepare and clean .zip files
        run: |
          echo "Removing existing .zip files, if any..."
          rm -f sphax_patch_pack/*.zip || echo "No .zip files to remove."

      - name: Debug listing before zipping
        run: |
          echo "Listing contents of sphax_patch_pack/ before zipping:"
          ls -al sphax_patch_pack/
          echo "Listing contents of x32-TCP-Sphax_PatchPack:"
          ls -al sphax_patch_pack/x32-TCP-Sphax_PatchPack

      - name: Create zip for x32-TCP-Sphax_PatchPack
        run: |
          echo "Creating x32-TCP-Sphax_PatchPack.zip..."
          cd sphax_patch_pack/x32-TCP-Sphax_PatchPack || exit 1
          zip -r ../../x32-TCP-Sphax_PatchPack.zip ./* || exit 1

      - name: Create zip for x64-TCP-Sphax_PatchPack
        run: |
          echo "Creating x64-TCP-Sphax_PatchPack.zip..."
          cd sphax_patch_pack/x64-TCP-Sphax_PatchPack || exit 1
          zip -r ../../x64-TCP-Sphax_PatchPack.zip ./* || exit 1

      - name: Create zip for x128-TCP-Sphax_PatchPack
        run: |
          echo "Creating x128-TCP-Sphax_PatchPack.zip..."
          cd sphax_patch_pack/x128-TCP-Sphax_PatchPack || exit 1
          zip -r ../../x128-TCP-Sphax_PatchPack.zip ./* || exit 1

      - name: Debug listing after zipping
        run: |
          echo "Listing contents of sphax_patch_pack/ after zipping:"
          ls -al sphax_patch_pack/

      - name: Commit and push the .zip files to the repository with Git LFS
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add sphax_patch_pack/*.zip
          git commit -m "Add .zip files for patched folders"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
